Tugas: Preprocessing Data (Analisis Dataset Features & Labels)

In [30]:
# Import library yang dibutuhkan
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

 1. Menampilkan data yang telah diunduh dan penjelasan semua kolom yang terdapat pada dataset

In [35]:
# Membaca dataset features dan labels
features = pd.read_csv("train_features.csv")
labels = pd.read_csv("train_labels.csv")

In [58]:
# Menampilkan masing-masing dataset
print("=== Data Features ===")
display(features)

print("\n=== Data Labels ===")
display(labels)

=== Data Features ===

,tahun_kelahiran,pendidikan,status_pernikahan,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,tanggal_menjadi_anggota
0,1979,Sarjana,Rencana Menikah,NaN,0.0,1.0,NaN,50575.0,260967.0,50575.0,20230.0,2.0,2.0,5.0,0.0,2014-05-05
1,1950,Sarjana,Rencana Menikah,84063000.0,NaN,NaN,70.0,6069.0,44506.0,80920.0,20230.0,9.0,6.0,4.0,0.0,2013-03-17
2,1966,Sarjana,Menikah,127532564.0,0.0,0.0,45.0,117611.0,265460.0,96341.0,145573.0,1.0,1.0,7.0,0.0,NaN
3,1961,Magister,Rencana Menikah,165579620.0,0.0,0.0,90.0,206346.0,1613901.0,27725.0,125868.0,0.0,7.0,8.0,0.0,NaN
4,1970,Sarjana,Rencana Menikah,117703159.0,1.0,1.0,78.0,90563.0,311757.0,40358.0,33875.0,7.0,6.0,5.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3812,1955,Magister,Menikah,78199470.0,0.0,0.0,33.0,6069.0,25977.0,3856.0,5784.0,5.0,1.0,0.0,0.0,NaN
3813,1947,Doktor,Rencana Menikah,109306000.0,0.0,1.0,44.0,0.0,50575.0,NaN,0.0,3.0,6.0,3.0,0.0,2014-06-09
3814,1974,Magister,Menikah,104621000.0,0.0,2.0,68.0,2023.0,62713.0,8092.0,0.0,7.0,5.0,7.0,0.0,2013-11-07
3815,1957,SMA,Rencana Menikah,110850000.0,1.0,1.0,67.0,18207.0,70805.0,24276.0,NaN,4.0,5.0,4.0,0.0,2013-06-30
3816,1961,Sarjana,Menikah,130512000.0,0.0,0.0,70.0,329749.0,600831.0,420784.0,161840.0,3.0,7.0,15.0,0.0,2014-01-25

=== Data Labels ===

      jumlah_promosi
0                  2
1                  0
2                  1
3                  4
4                  4
...              ...
3812               5
3813               1
3814               0
3815               0
3816               0

[3817 rows x 1 columns]

Penjelasan kolom

---

Dataset train_features.csv berisi informasi detail tentang pelanggan, yaitu:
- tahun_kelahiran           : Tahun kelahiran pelanggan.
- pendidikan                : Tingkat pendidikan terakhir pelanggan.
- status_pernikahan         : Status pernikahan (menikah/belum menikah).
- pendapatan                : Total pendapatan pelanggan.
- jumlah_anak_balita        : Jumlah anak di bawah usia 5 tahun.
- jumlah_anak_remaja        : Jumlah anak berusia remaja di rumah.
- terakhir_belanja          : Jumlah hari sejak terakhir kali pelanggan berbelanja.
- belanja_buah              : Jumlah pengeluaran untuk buah.
- belanja_daging            : Jumlah pengeluaran untuk daging.
- belanja_ikan              : Jumlah pengeluaran untuk ikan.
- belanja_kue               : Jumlah pengeluaran untuk kue.
- pembelian_diskon          : Jumlah pembelian yang dilakukan dengan diskon.
- pembelian_web             : Jumlah pembelian melalui website.
- pembelian_toko            : Jumlah pembelian langsung di toko.
- keluhan                   : Jumlah keluhan yang diajukan pelanggan.
- tanggal_menjadi_anggota   : Tanggal pertama kali pelanggan menjadi anggota.

Dataset train_labels.csv berisi:
- jumlah_promosi            : Banyaknya promosi yang diterima atau diikuti pelanggan.

---

2. Melakukan agregasi antara tabel features dengan tabel labels

In [44]:
# Menggabungkan kedua tabel berdasarkan index
merged = pd.concat([features, labels], axis=1)

# Menampilkan beberapa baris awal hasil penggabungan
print("\n=== Dataset Setelah Digabungkan ===")
display(merged.head())

=== Dataset Setelah Digabungkan ===

,tahun_kelahiran,pendidikan,status_pernikahan,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,tanggal_menjadi_anggota,jumlah_promosi
0,1979,Sarjana,Rencana Menikah,NaN,0.0,1.0,NaN,50575.0,260967.0,50575.0,20230.0,2.0,2.0,5.0,0.0,2014-05-05,2
1,1950,Sarjana,Rencana Menikah,84063000.0,NaN,NaN,70.0,6069.0,44506.0,80920.0,20230.0,9.0,6.0,4.0,0.0,2013-03-17,0
2,1966,Sarjana,Menikah,127532564.0,0.0,0.0,45.0,117611.0,265460.0,96341.0,145573.0,1.0,1.0,7.0,0.0,NaN,1
3,1961,Magister,Rencana Menikah,165579620.0,0.0,0.0,90.0,206346.0,1613901.0,27725.0,125868.0,0.0,7.0,8.0,0.0,NaN,4
4,1970,Sarjana,Rencana Menikah,117703159.0,1.0,1.0,78.0,90563.0,311757.0,40358.0,33875.0,7.0,6.0,5.0,0.0,NaN,4


---


- Proses agregasi dilakukan dengan menggabungkan (merge) tabel features dan labels
berdasarkan urutan baris yang sama (index).
- Hasilnya adalah dataset baru bernama "merged" yang berisi semua kolom fitur pelanggan serta kolom target (jumlah_promosi).
- Dataset hasil penggabungan ini akan digunakan untuk langkah-langkah analisis dan preprocessing berikutnya.


---

3. Menampilkan tipe data dari setiap kolom yang terdapat dalam dataset

In [51]:
print("\n=== Tipe Data Setiap Kolom ===")
print(merged.dtypes)

=== Tipe Data Setiap Kolom ===
tahun_kelahiran              int64
pendidikan                  object
status_pernikahan           object
pendapatan                 float64
jumlah_anak_balita         float64
jumlah_anak_remaja         float64
terakhir_belanja           float64
belanja_buah               float64
belanja_daging             float64
belanja_ikan               float64
belanja_kue                float64
pembelian_diskon           float64
pembelian_web              float64
pembelian_toko             float64
keluhan                    float64
tanggal_menjadi_anggota     object
jumlah_promosi               int64
dtype: object

4. Menampilkan statistik deskriptif dari dataset dan berikan analisis singkat mengenai hasilnya

In [52]:
merged.describe()

,tahun_kelahiran,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,jumlah_promosi
count,3817.000000,3.627000e+03,3627.000000,3613.000000,3645.000000,3636.000000,3.639000e+03,3624.000000,3603.000000,3639.000000,3652.000000,3648.000000,3621.000000,3817.000000
mean,1967.823946,1.144832e+08,0.293080,0.353723,47.231550,59804.239824,4.385748e+05,81428.997792,63377.970580,2.125584,4.436473,5.767818,0.004971,2.585800
std,11.768131,4.346042e+07,0.473063,0.493014,27.068512,74024.976109,5.120427e+05,99976.226855,79435.457282,2.100133,3.002522,3.210738,0.070340,2.101845
min,1899.000000,5.073000e+06,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1959.000000,8.112512e+07,0.000000,0.000000,25.000000,7907.000000,4.947950e+04,10115.000000,7947.000000,0.000000,2.000000,3.000000,0.000000,0.000000
50%,1968.000000,1.156214e+08,0.000000,0.000000,47.000000,26456.000000,2.219930e+05,36054.500000,27795.000000,2.000000,4.000000,5.000000,0.000000,3.000000
75%,1976.000000,1.504960e+08,1.000000,1.000000,69.000000,86162.000000,6.863555e+05,121380.000000,89502.500000,3.000000,7.000000,8.000000,0.000000,4.000000
max,2000.000000,3.328840e+08,2.000000,2.000000,128.000000,396508.000000,3.489675e+06,621600.000000,542164.000000,20.000000,30.000000,17.000000,1.000000,6.000000



---


Analisis singkat:
- Dari hasil statistik deskriptif, perhatikan nilai mean, std, min, dan max.
- Jika selisih antara mean dan median jauh, kemungkinan data memiliki outlier.
- Cek juga jumlah nilai unik untuk kolom bertipe object.


---

5. Slicing Data

In [55]:
print("\n=== 20 Baris Awal Dataset ===")
display(merged.head(20))

print("\n=== 20 Baris Terakhir Dataset ===")
display(merged.tail(20))

print("\n=== Baris dari index 80 - 100 ===")
display(merged.iloc[80:101])

=== 20 Baris Awal Dataset ===

,tahun_kelahiran,pendidikan,status_pernikahan,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,tanggal_menjadi_anggota,jumlah_promosi
0,1979,Sarjana,Rencana Menikah,NaN,0.0,1.0,NaN,50575.0,260967.0,50575.0,20230.0,2.0,2.0,5.0,0.0,2014-05-05,2
1,1950,Sarjana,Rencana Menikah,84063000.0,NaN,NaN,70.0,6069.0,44506.0,80920.0,20230.0,9.0,6.0,4.0,0.0,2013-03-17,0
2,1966,Sarjana,Menikah,127532564.0,0.0,0.0,45.0,117611.0,265460.0,96341.0,145573.0,1.0,1.0,7.0,0.0,NaN,1
3,1961,Magister,Rencana Menikah,165579620.0,0.0,0.0,90.0,206346.0,1613901.0,27725.0,125868.0,0.0,7.0,8.0,0.0,NaN,4
4,1970,Sarjana,Rencana Menikah,117703159.0,1.0,1.0,78.0,90563.0,311757.0,40358.0,33875.0,7.0,6.0,5.0,0.0,NaN,4
5,1952,Magister,Sendiri,94346105.0,0.0,0.0,9.0,33509.0,49228.0,0.0,NaN,1.0,4.0,2.0,0.0,NaN,5
6,1963,Magister,Sendiri,75313000.0,2.0,NaN,96.0,0.0,14161.0,8092.0,2023.0,1.0,4.0,5.0,0.0,2013-05-03,0
7,1959,Sarjana,Rencana Menikah,137916316.0,0.0,0.0,21.0,38505.0,1146659.0,192956.0,240718.0,4.0,NaN,6.0,0.0,NaN,5
8,1957,Sarjana,Sendiri,138069883.0,0.0,0.0,26.0,56486.0,NaN,193754.0,202737.0,3.0,9.0,5.0,0.0,NaN,5
9,1975,Sarjana,Menikah,37567504.0,1.0,NaN,67.0,19061.0,28067.0,22223.0,14146.0,3.0,2.0,1.0,0.0,NaN,2
10,1953,Sarjana,Sendiri,34471060.0,0.0,0.0,59.0,14835.0,20379.0,18507.0,6893.0,3.0,1.0,5.0,0.0,NaN,2
11,1968,SMA,Menikah,142698390.0,0.0,1.0,57.0,330825.0,218283.0,79147.0,324377.0,1.0,8.0,12.0,0.0,NaN,1
12,1957,Sarjana,Sendiri,152418000.0,0.0,NaN,5.0,149702.0,337841.0,93058.0,72828.0,3.0,10.0,2.0,0.0,2013-11-21,4
13,1979,SMP,Menikah,14967000.0,NaN,0.0,65.0,34391.0,30345.0,32368.0,0.0,0.0,5.0,2.0,0.0,2012-11-14,0
14,1983,Sarjana,Menikah,87587900.0,1.0,0.0,61.0,8121.0,420520.0,44254.0,23153.0,4.0,8.0,6.0,0.0,NaN,2
15,1961,Magister,Rencana Menikah,107962505.0,0.0,1.0,45.0,9783.0,121506.0,14412.0,21201.0,3.0,2.0,5.0,0.0,NaN,3
16,1977,Doktor,Menikah,78371000.0,1.0,0.0,25.0,4046.0,22253.0,10115.0,6069.0,2.0,3.0,0.0,0.0,NaN,1
17,1973,Sarjana,Rencana Menikah,119766595.0,NaN,1.0,16.0,20230.0,181594.0,10650.0,51288.0,0.0,7.0,8.0,0.0,NaN,3
18,1969,Sarjana,Menikah,51837000.0,1.0,0.0,0.0,6069.0,10115.0,10115.0,10115.0,0.0,0.0,2.0,0.0,2013-06-23,0
19,1980,SMA,Sendiri,100650216.0,0.0,0.0,50.0,10115.0,3225667.0,16104.0,14022.0,0.0,0.0,2.0,0.0,NaN,3

=== 20 Baris Terakhir Dataset ===

,tahun_kelahiran,pendidikan,status_pernikahan,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,tanggal_menjadi_anggota,jumlah_promosi
3797,1982,NaN,Sendiri,120689156.0,0.0,0.0,74.0,NaN,350942.0,44583.0,17614.0,2.0,5.0,12.0,0.0,NaN,4
3798,1968,Sarjana,Sendiri,124682000.0,NaN,1.0,48.0,26299.0,515865.0,24276.0,34391.0,2.0,5.0,14.0,0.0,2012-11-09,4
3799,1972,Sarjana,Sendiri,49354000.0,1.0,1.0,2.0,6069.0,22253.0,0.0,0.0,3.0,1.0,2.0,0.0,NaN,1
3800,1973,Magister,Rencana Menikah,94141211.0,0.0,1.0,69.0,65292.0,140778.0,126206.0,106133.0,7.0,2.0,6.0,0.0,NaN,3
3801,1973,NaN,Sendiri,171296541.0,0.0,0.0,38.0,38261.0,661232.0,362908.0,51052.0,1.0,10.0,10.0,0.0,NaN,1
3802,1959,Sarjana,Menikah,76899323.0,1.0,1.0,84.0,1113.0,17390.0,5159.0,0.0,0.0,0.0,3.0,0.0,NaN,1
3803,1969,Sarjana,Menikah,NaN,1.0,0.0,16.0,77055.0,362195.0,31759.0,29808.0,1.0,5.0,11.0,0.0,NaN,4
3804,1965,Magister,Menikah,NaN,0.0,0.0,93.0,204236.0,NaN,40104.0,138478.0,NaN,8.0,8.0,0.0,NaN,4
3805,1950,Doktor,Menikah,122606074.0,0.0,1.0,5.0,20495.0,155440.0,27874.0,2842.0,5.0,8.0,8.0,0.0,NaN,0
3806,1958,Sarjana,NaN,109027112.0,0.0,1.0,97.0,15945.0,164454.0,13327.0,952.0,4.0,10.0,5.0,0.0,NaN,5
3807,1976,Magister,Sendiri,162847930.0,0.0,0.0,27.0,95867.0,705486.0,164391.0,135721.0,1.0,6.0,8.0,0.0,NaN,5
3808,1963,Magister,NaN,117190625.0,0.0,1.0,69.0,2545.0,106247.0,1044.0,11880.0,1.0,3.0,11.0,0.0,NaN,3
3809,1971,Magister,Menikah,113691000.0,0.0,1.0,62.0,10115.0,147679.0,10115.0,NaN,3.0,8.0,4.0,0.0,2013-12-15,1
3810,1990,SMA,Sendiri,50284000.0,0.0,0.0,0.0,12138.0,8092.0,8092.0,NaN,0.0,0.0,5.0,0.0,2014-02-05,0
3811,1988,SMA,Menikah,165054524.0,0.0,0.0,11.0,37316.0,729052.0,45582.0,51913.0,1.0,3.0,8.0,0.0,NaN,5
3812,1955,Magister,Menikah,78199470.0,0.0,0.0,33.0,6069.0,25977.0,3856.0,5784.0,5.0,1.0,0.0,0.0,NaN,5
3813,1947,Doktor,Rencana Menikah,109306000.0,0.0,1.0,44.0,0.0,50575.0,NaN,0.0,3.0,6.0,3.0,0.0,2014-06-09,1
3814,1974,Magister,Menikah,104621000.0,0.0,2.0,68.0,2023.0,62713.0,8092.0,0.0,7.0,5.0,7.0,0.0,2013-11-07,0
3815,1957,SMA,Rencana Menikah,110850000.0,1.0,1.0,67.0,18207.0,70805.0,24276.0,NaN,4.0,5.0,4.0,0.0,2013-06-30,0
3816,1961,Sarjana,Menikah,130512000.0,0.0,0.0,70.0,329749.0,600831.0,420784.0,161840.0,3.0,7.0,15.0,0.0,2014-01-25,0

=== Baris dari index 80 - 100 ===

,tahun_kelahiran,pendidikan,status_pernikahan,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,tanggal_menjadi_anggota,jumlah_promosi
80,1961,Sarjana,Sendiri,152276450.0,0.0,0.0,20.0,118419.0,390780.0,114113.0,75835.0,2.0,9.0,4.0,0.0,NaN,4
81,1973,Magister,Rencana Menikah,165458484.0,0.0,0.0,60.0,282725.0,1520515.0,148755.0,125538.0,NaN,5.0,8.0,0.0,NaN,4
82,1968,Sarjana,Cerai,172329809.0,0.0,0.0,20.0,196777.0,774778.0,231114.0,287046.0,NaN,6.0,4.0,0.0,NaN,6
83,1979,Sarjana,Menikah,138817313.0,0.0,0.0,6.0,44506.0,931955.0,256516.0,60244.0,0.0,6.0,8.0,0.0,NaN,5
84,1962,SMA,Rencana Menikah,110928081.0,0.0,1.0,77.0,10634.0,46775.0,2815.0,1585.0,4.0,5.0,5.0,0.0,NaN,5
85,1974,Magister,Menikah,151599910.0,0.0,0.0,22.0,28441.0,514556.0,44208.0,25168.0,1.0,3.0,8.0,0.0,NaN,1
86,1971,Sarjana,Rencana Menikah,111202436.0,0.0,1.0,50.0,83817.0,382409.0,81305.0,235977.0,3.0,5.0,4.0,0.0,NaN,0
87,1975,Magister,NaN,164601983.0,0.0,0.0,NaN,66647.0,NaN,102878.0,121044.0,0.0,5.0,7.0,0.0,NaN,5
88,1947,SMA,Cerai,151115234.0,0.0,0.0,55.0,144766.0,1192829.0,258158.0,197764.0,2.0,7.0,10.0,0.0,NaN,1
89,1980,Magister,Menikah,105661000.0,0.0,0.0,77.0,32368.0,311542.0,139587.0,72828.0,0.0,6.0,5.0,0.0,2014-06-11,0
90,1958,Sarjana,Menikah,118634453.0,0.0,1.0,11.0,13677.0,112716.0,14951.0,747.0,1.0,9.0,3.0,0.0,NaN,0
91,1983,Sarjana,NaN,84414440.0,0.0,0.0,32.0,85187.0,322101.0,104424.0,72718.0,1.0,6.0,7.0,0.0,NaN,6
92,1954,Magister,NaN,100020844.0,0.0,0.0,75.0,24486.0,236354.0,17838.0,579.0,4.0,9.0,2.0,0.0,NaN,0
93,1964,Magister,Rencana Menikah,95020110.0,0.0,1.0,76.0,14152.0,149547.0,16167.0,14152.0,5.0,5.0,4.0,0.0,NaN,0
94,1958,Sarjana,Cerai,170112112.0,0.0,0.0,69.0,108681.0,1798060.0,133865.0,202370.0,0.0,4.0,4.0,0.0,NaN,3
95,1954,Sarjana,Menikah,136676591.0,0.0,1.0,87.0,196142.0,NaN,122599.0,159239.0,3.0,11.0,5.0,0.0,NaN,3
96,1959,Magister,Menikah,165583000.0,0.0,0.0,43.0,291312.0,236691.0,449106.0,295358.0,0.0,3.0,9.0,0.0,2013-03-31,2
97,1966,Sarjana,NaN,187041788.0,0.0,0.0,31.0,166150.0,1632669.0,312792.0,145162.0,2.0,4.0,4.0,0.0,NaN,0
98,1968,Sarjana,Sendiri,99416000.0,1.0,1.0,23.0,10115.0,109242.0,0.0,18207.0,6.0,7.0,2.0,0.0,2012-11-06,1
99,1962,Sarjana,Sendiri,152559603.0,0.0,0.0,11.0,131624.0,NaN,154939.0,47797.0,1.0,10.0,5.0,0.0,NaN,4
100,1968,Sarjana,Rencana Menikah,100686641.0,0.0,1.0,NaN,14524.0,63666.0,42277.0,18320.0,1.0,4.0,2.0,0.0,NaN,4

6. Menangani nilai yang hilang (NaN)

In [20]:
# Mengecek jumlah nilai NaN sebelum imputasi
print("\n=== Jumlah Nilai NaN Sebelum Imputasi ===")
print(merged.isna().sum())

=== Jumlah Nilai NaN Sebelum Imputasi ===
tahun_kelahiran               0
pendidikan                  189
status_pernikahan           212
pendapatan                  190
jumlah_anak_balita          190
jumlah_anak_remaja          204
terakhir_belanja            172
belanja_buah                181
belanja_daging              178
belanja_ikan                193
belanja_kue                 214
pembelian_diskon            178
pembelian_web               165
pembelian_toko              169
keluhan                     196
tanggal_menjadi_anggota    2752
jumlah_promosi                0
dtype: int64

In [21]:
# Menggunakan SimpleImputer (mean) untuk kolom numerik
num_cols = merged.select_dtypes(include=[np.number]).columns
imputer = SimpleImputer(strategy='mean')
merged[num_cols] = imputer.fit_transform(merged[num_cols])

Penjelasan


---

SimpleImputer melakukan imputasi otomatis berdasarkan strategi tertentu (mean, median, most_frequent, atau constant). Cocok digunakan untuk preprocessing dalam pipeline machine learning karena bentuknya sebagai object transformer.

- select_dtypes(include=[np.number]) → memilih semua kolom bertipe numerik (int atau float).

- SimpleImputer(strategy='mean') → membuat objek imputasi dari library sklearn untuk mengganti nilai yang hilang (NaN) dengan rata-rata (mean) dari setiap kolom.

- fit_transform() → dua proses dalam satu langkah:

- fit() menghitung nilai mean dari setiap kolom.

- transform() mengganti semua nilai NaN dengan mean yang sudah dihitung.

- merged[num_cols] = ... → hasil imputasi dimasukkan kembali ke kolom numerik di dataset merged.

---

In [22]:
# Mengecek kembali setelah imputasi
print("\n=== Jumlah Nilai NaN Setelah Imputasi ===")
print(merged.isna().sum())

=== Jumlah Nilai NaN Setelah Imputasi ===
tahun_kelahiran               0
pendidikan                  189
status_pernikahan           212
pendapatan                    0
jumlah_anak_balita            0
jumlah_anak_remaja            0
terakhir_belanja              0
belanja_buah                  0
belanja_daging                0
belanja_ikan                  0
belanja_kue                   0
pembelian_diskon              0
pembelian_web                 0
pembelian_toko                0
keluhan                       0
tanggal_menjadi_anggota    2752
jumlah_promosi                0
dtype: int64

7. Encoding terhadap kolom bertipe object menjadi numerik

In [23]:
# Menemukan kolom bertipe object (kategorikal)
cat_cols = merged.select_dtypes(include=['object']).columns
print("\n=== Kolom Kategorikal ===")
print(cat_cols)

=== Kolom Kategorikal ===
Index(['pendidikan', 'status_pernikahan', 'tanggal_menjadi_anggota'], dtype='object')

In [60]:
# Menggunakan LabelEncoder
encoder = LabelEncoder()
for col in cat_cols:
    merged[col] = encoder.fit_transform(merged[col].astype(str))

print("\n=== Dataset Setelah Encoding ===")
display(merged)

=== Dataset Setelah Encoding ===

,tahun_kelahiran,pendidikan,status_pernikahan,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,tanggal_menjadi_anggota,jumlah_promosi
0,1979,5,4,NaN,0.0,1.0,NaN,50575.0,260967.0,50575.0,20230.0,2.0,2.0,5.0,0.0,519,2
1,1950,5,4,84063000.0,NaN,NaN,70.0,6069.0,44506.0,80920.0,20230.0,9.0,6.0,4.0,0.0,186,0
2,1966,5,3,127532564.0,0.0,0.0,45.0,117611.0,265460.0,96341.0,145573.0,1.0,1.0,7.0,0.0,564,1
3,1961,2,4,165579620.0,0.0,0.0,90.0,206346.0,1613901.0,27725.0,125868.0,0.0,7.0,8.0,0.0,564,4
4,1970,5,4,117703159.0,1.0,1.0,78.0,90563.0,311757.0,40358.0,33875.0,7.0,6.0,5.0,0.0,564,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3812,1955,2,3,78199470.0,0.0,0.0,33.0,6069.0,25977.0,3856.0,5784.0,5.0,1.0,0.0,0.0,564,5
3813,1947,1,4,109306000.0,0.0,1.0,44.0,0.0,50575.0,NaN,0.0,3.0,6.0,3.0,0.0,547,1
3814,1974,2,3,104621000.0,0.0,2.0,68.0,2023.0,62713.0,8092.0,0.0,7.0,5.0,7.0,0.0,375,0
3815,1957,3,4,110850000.0,1.0,1.0,67.0,18207.0,70805.0,24276.0,NaN,4.0,5.0,4.0,0.0,270,0
3816,1961,5,3,130512000.0,0.0,0.0,70.0,329749.0,600831.0,420784.0,161840.0,3.0,7.0,15.0,0.0,435,0

8. Menampilkan kembali dataset hasil preprocessing

In [63]:
print("\n=== Dataset Setelah Semua Tahapan Preprocessing ===")
display(merged)

# Mengecek apakah masih ada nilai NaN atau tipe data tidak sesuai
print("\n=== Cek Nilai NaN Setelah Semua Tahapan ===")
print(merged.isna().sum())

print("\n=== Cek Tipe Data Akhir ===")
print(merged.dtypes)

=== Dataset Setelah Semua Tahapan Preprocessing ===

,tahun_kelahiran,pendidikan,status_pernikahan,pendapatan,jumlah_anak_balita,jumlah_anak_remaja,terakhir_belanja,belanja_buah,belanja_daging,belanja_ikan,belanja_kue,pembelian_diskon,pembelian_web,pembelian_toko,keluhan,tanggal_menjadi_anggota,jumlah_promosi
0,1979,5,4,NaN,0.0,1.0,NaN,50575.0,260967.0,50575.0,20230.0,2.0,2.0,5.0,0.0,519,2
1,1950,5,4,84063000.0,NaN,NaN,70.0,6069.0,44506.0,80920.0,20230.0,9.0,6.0,4.0,0.0,186,0
2,1966,5,3,127532564.0,0.0,0.0,45.0,117611.0,265460.0,96341.0,145573.0,1.0,1.0,7.0,0.0,564,1
3,1961,2,4,165579620.0,0.0,0.0,90.0,206346.0,1613901.0,27725.0,125868.0,0.0,7.0,8.0,0.0,564,4
4,1970,5,4,117703159.0,1.0,1.0,78.0,90563.0,311757.0,40358.0,33875.0,7.0,6.0,5.0,0.0,564,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3812,1955,2,3,78199470.0,0.0,0.0,33.0,6069.0,25977.0,3856.0,5784.0,5.0,1.0,0.0,0.0,564,5
3813,1947,1,4,109306000.0,0.0,1.0,44.0,0.0,50575.0,NaN,0.0,3.0,6.0,3.0,0.0,547,1
3814,1974,2,3,104621000.0,0.0,2.0,68.0,2023.0,62713.0,8092.0,0.0,7.0,5.0,7.0,0.0,375,0
3815,1957,3,4,110850000.0,1.0,1.0,67.0,18207.0,70805.0,24276.0,NaN,4.0,5.0,4.0,0.0,270,0
3816,1961,5,3,130512000.0,0.0,0.0,70.0,329749.0,600831.0,420784.0,161840.0,3.0,7.0,15.0,0.0,435,0

=== Cek Nilai NaN Setelah Semua Tahapan ===
tahun_kelahiran              0
pendidikan                   0
status_pernikahan            0
pendapatan                 190
jumlah_anak_balita         190
jumlah_anak_remaja         204
terakhir_belanja           172
belanja_buah               181
belanja_daging             178
belanja_ikan               193
belanja_kue                214
pembelian_diskon           178
pembelian_web              165
pembelian_toko             169
keluhan                    196
tanggal_menjadi_anggota      0
jumlah_promosi               0
dtype: int64

=== Cek Tipe Data Akhir ===
tahun_kelahiran              int64
pendidikan                   int64
status_pernikahan            int64
pendapatan                 float64
jumlah_anak_balita         float64
jumlah_anak_remaja         float64
terakhir_belanja           float64
belanja_buah               float64
belanja_daging             float64
belanja_ikan               float64
belanja_kue                float64
pembelian_diskon           float64
pembelian_web              float64
pembelian_toko             float64
keluhan                    float64
tanggal_menjadi_anggota      int64
jumlah_promosi               int64
dtype: object